import type {
GoalCard
} from "@/components/finance/goals/goals-types";

export interface GoalsViewDiv2Props {
  dashboard: { investmentProjection: { currentBalanceCents: number; asOfDate: string; estimatedInterestCents: number; contributionCents: number; withdrawalCents: number; netMovementCents: number; projection: { [k: string]: number; }; plannedMovements: import("@/lib/investment-projection").InvestmentMovement[]; nextContributionDate: string | undefined; createdAt: Date & string; id: string; updatedAt: Date & string; checkpointBalanceCents: number; expectedMonthlyRateBps: number; checkpointDate: string; } | null; summary: { investmentBalanceCents: number; totalAllocatedCents: number; freeReserveCents: number; remainingToGoalsCents: number; monthlyRequiredCents: number; monthlyPlannedContributionCents: number; goalCount: number; archivedGoalCount: number; }; goals: { targetDate: string | null; allocatedCents: number; remainingCents: number; overfundedCents: number; progressPercentage: number; monthlyRequiredCents: number; name: string; createdAt: Date & string; id: string; updatedAt: Date & string; status: "active" | "paused" | "completed" | "archived"; notes: string | null; targetAmountCents: number; color: string; category: "housing" | "vehicle" | "electronics" | "travel" | "education" | "emergency" | "other"; plannedMonthlyContributionCents: number; priority: number; }[]; archivedGoals: { targetDate: string | null; allocatedCents: number; remainingCents: number; overfundedCents: number; progressPercentage: number; monthlyRequiredCents: number; name: string; createdAt: Date & string; id: string; updatedAt: Date & string; status: "active" | "paused" | "completed" | "archived"; notes: string | null; targetAmountCents: number; color: string; category: "housing" | "vehicle" | "electronics" | "travel" | "education" | "emergency" | "other"; plannedMonthlyContributionCents: number; priority: number; }[]; charts: { allocationBreakdown: { id: string; name: string; amountCents: number; color: string; }[]; monthlyEvolution: { cumulativeAllocatedCents: number; monthlyAllocatedCents: number; monthlyContributionCents: number; monthlyReleasedCents: number; netMovementCents: number; month: string; }[]; }; recentAllocations: { goalName: string; goalColor: string; createdAt: Date & string; id: string; type: "initial_allocation" | "manual_allocation" | "manual_release" | "contribution" | "correction"; updatedAt: Date & string; amountCents: number; notes: string | null; transactionId: string | null; occurredOn: string; goalId: string; }[]; options: { sourceAccounts: { id: string; name: string; }[]; investmentCategories: { id: string; name: string; }[]; goalCategories: ("housing" | "vehicle" | "electronics" | "travel" | "education" | "emergency" | "other")[]; goalStatuses: ("active" | "paused" | "completed" | "archived")[]; allocationTypes: ("initial_allocation" | "manual_allocation" | "manual_release" | "contribution" | "correction")[]; }; };
  openAllocationDialog: (goal: GoalCard, type: "manual_allocation" | "manual_release") => void;
  openContributionDialog: (goal: GoalCard) => void;
  openEditGoal: (goal: GoalCard) => void;
  setArchiveGoal: import("react").Dispatch<import("react").SetStateAction<{ targetDate: string | null; allocatedCents: number; remainingCents: number; overfundedCents: number; progressPercentage: number; monthlyRequiredCents: number; name: string; createdAt: Date & string; id: string; updatedAt: Date & string; status: "active" | "paused" | "completed" | "archived"; notes: string | null; targetAmountCents: number; color: string; category: "housing" | "vehicle" | "electronics" | "travel" | "education" | "emergency" | "other"; plannedMonthlyContributionCents: number; priority: number; } | null>>;
  canCreateContribution: boolean;
  isMutating: boolean;
  openCreateGoal: () => void;
}
