
export interface CalculateCreditCardInvoiceSummaryContext {
  invoiceEntries: import("@/lib/server/credit-card").CreditCardExpenseEntry[];
  monthTransactions: { fundingSource: "account" | "investments"; fundingLink: import("@/lib/interfaces/transaction-funding").TransactionFundingLink | null; isGeneratedByFunding: boolean; account: ({ id: string; name: string; type: "checking" | "savings" | "cash" | "credit" | "investment"; initialBalanceCents: number; creditClosingDay: number | null; creditDueDay: number; isArchived: boolean; nameHash: string | null; createdAt: Date; updatedAt: Date; } & { createdAt: string | undefined; updatedAt: string | undefined; }) | null; category: ({ id: string; name: string; isArchived: boolean; nameHash: string | null; createdAt: Date; updatedAt: Date; group: "investment" | "income" | "fixed_expense" | "variable_expense"; } & { createdAt: string | undefined; updatedAt: string | undefined; }) | null; id: string; type: "income" | "expense" | "investment_contribution" | "investment_withdrawal"; createdAt: Date & string; updatedAt: Date & string; accountId: string; status: "pending" | "posted" | "cancelled"; categoryId: string | null; amountCents: number; description: string; recurringTemplateId: string | null; transactionDate: string; competenceMonth: string; notes: string | null; importFingerprint: string | null; isIncludedInInvestmentCheckpoint: boolean; importFingerprintHash: string | null; competenceMonthHash: string | null; }[];
  paymentTransactionIds: Set<string>;
  bill: { id: string; createdAt: Date; updatedAt: Date; accountId: string; invoiceMonth: string; dueDate: string; statementTotalCents: number; currentChargesTotalCents: number; priorBalanceCents: number; preStatementPaymentsCents: number; ignoredAmountCents: number; status: "open" | "paid"; paidAt: string | null; invoiceMonthHash: string | null; payments: { id: string; createdAt: Date; updatedAt: Date; billId: string | null; amountCents: number; transactionId: string; paymentDate: string; kind: "pre_statement" | "settlement" | "unlinked"; idempotencyKey: string; idempotencyKeyHash: string | null; }[]; } | undefined;
  futureChargeRows: { id: string; createdAt: Date; updatedAt: Date; accountId: string; categoryId: string; description: string; notes: string | null; importFingerprint: string | null; importFingerprintHash: string | null; kind: "purchase" | "adjustment"; purchaseDate: string; totalAmountCents: number; installmentCount: number; firstInvoiceMonth: string; category: { id: string; name: string; isArchived: boolean; nameHash: string | null; createdAt: Date; updatedAt: Date; group: "investment" | "income" | "fixed_expense" | "variable_expense"; }; installments: { id: string; createdAt: Date; updatedAt: Date; invoiceMonth: string; amountCents: number; chargeId: string; installmentNumber: number; installmentNumberHash: string | null; }[]; }[];
  normalizedMonth: string;
}
