import { test, expect } from "./helpers/fixture";

test("creates, edits, copies and removes monthly limits on mobile with expense drilldown", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/budgets?month=2026-07");
  await expect(page.getByRole("heading", { name: "Orçamentos", exact: true })).toBeVisible();
  const category = page.getByRole("combobox");
  const option = category.locator("option").filter({ hasText: "Lazer" });
  await category.selectOption(await option.getAttribute("value") as string);
  await page.getByRole("textbox", { name: "Limite mensal (R$)" }).fill("800,00");
  await page.getByRole("textbox", { name: "Limite mensal (R$)" }).press("Enter");
  const row = page.getByRole("article", { name: "Lazer", exact: true });
  await expect(row.getByRole("progressbar")).toBeVisible();
  await row.getByText(/Conferir despesas de Lazer/).press("Enter");
  await expect(row.getByText(/Lançamento|Parcela|Recorrência gerada/).first()).toBeVisible();
  await row.getByText("Editar limite de Lazer").click();
  await row.getByRole("textbox", { name: "Limite de Lazer" }).fill("900,00");
  await row.getByRole("button", { name: "Salvar limite" }).click();
  await expect(row).toContainText("900,00");
  await page.goto("/budgets?month=2026-08");
  await page.getByRole("button", { name: "Copiar limites do mês anterior" }).click();
  await expect(row.getByRole("progressbar")).toBeVisible();
  await row.getByText("Editar limite de Lazer").click();
  await row.getByRole("textbox").fill("700,00");
  await row.getByRole("button", { name: "Salvar limite" }).click();
  await expect(row).toContainText("700,00");
  await page.getByRole("button", { name: "Copiar limites do mês anterior" }).click();
  await expect(page.getByText("0 limite(s) copiado(s). Valores existentes preservados.")).toBeVisible();
  await expect(row).toContainText("700,00");
  await page.reload();
  await expect(row).toContainText("700,00");
  await row.getByText("Editar limite de Lazer").click();
  await row.getByRole("button", { name: "Remover limite" }).click();
  await expect(row.getByRole("progressbar")).toHaveCount(0);
  await page.goto("/budgets?month=2026-07");
  await expect(row).toContainText("900,00");
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth);
  expect(overflow).toBe(false);
});
