import { ArrowUpRight, CalendarDays, Check, Target } from "lucide-react";
import type { LoginPreviewProps } from "@/lib/interfaces/login-preview";

export function LoginPreview({ variant }: LoginPreviewProps) {
  return (
    <div aria-hidden="true" className="relative mx-auto w-full max-w-[410px] select-none rounded-2xl border border-border bg-surface-raised p-5 text-left shadow-[0_24px_60px_-20px_rgba(0,0,0,0.22)] sm:p-6">
      <div className="mb-6 flex items-center justify-between border-b border-border pb-4"><span className="text-sm font-semibold">{variant === "overview" ? "Visão mensal" : variant === "planning" ? "Seu mês, organizado" : "Planos que ganham forma"}</span><span className="rounded-md bg-surface px-2 py-1 text-[10px] text-content">{variant === "goals" ? "Minhas metas" : "Outubro"}</span></div>
      {variant === "overview" ? <>
        <div className="grid grid-cols-3 gap-2">{[{ label: "Receitas", value: "4.800", color: "text-success" }, { label: "Despesas", value: "1.650", color: "text-orange" }, { label: "Investimentos", value: "2.000", color: "text-brand" }].map(item => <div key={item.label} className="rounded-lg border border-border p-2.5"><p className="text-[9px] text-content">{item.label}</p><p className="mt-2 text-xs font-semibold sm:text-sm">R$ {item.value}</p><ArrowUpRight className={`mt-2 size-3 ${item.color}`} /></div>)}</div>
        <div className="mt-5 rounded-xl bg-surface p-3"><div className="flex justify-between text-[10px]"><span className="text-content">Evolução do saldo</span><span className="text-success">+18,6%</span></div><svg viewBox="0 0 340 120" className="mt-3 w-full fill-none"><path d="M0 25H340M0 65H340M0 105H340" stroke="var(--border)" /><path d="M0 105 55 82 110 88 170 52 225 63 280 28 340 12V120H0Z" fill="var(--brand)" opacity=".08" /><path d="M0 105 55 82 110 88 170 52 225 63 280 28 340 12" stroke="var(--brand)" strokeWidth="3" strokeLinejoin="round" /><path d="M0 110 55 104 110 110 170 88 225 95 280 76 340 82" stroke="var(--orange)" strokeWidth="2" /></svg><div className="mt-2 flex justify-between text-[9px] text-content-muted"><span>MAI</span><span>JUN</span><span>JUL</span><span>AGO</span><span>SET</span><span>OUT</span></div></div>
      </> : variant === "planning" ? <>
        <div className="mb-5 flex items-center gap-3"><span className="rounded-xl bg-brand-soft p-3 text-brand"><CalendarDays className="size-5" /></span><div><p className="text-[10px] text-content">Compromissos do mês</p><p className="mt-1 text-xl font-semibold">Tudo no seu radar.</p></div></div>
        {[{ day: "05", name: "Salário", category: "Receita recorrente", value: "+ R$ 4.800", positive: true }, { day: "10", name: "Aluguel", category: "Moradia", value: "R$ 1.200", positive: false }, { day: "15", name: "Cartão de crédito", category: "Fatura do mês", value: "R$ 450", positive: false }].map(item => <div key={item.day} className="flex items-center gap-3 border-t border-border py-3.5"><span className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-surface text-xs font-semibold">{item.day}</span><div className="flex-1"><p className="text-xs font-medium">{item.name}</p><p className="mt-1 text-[10px] text-content-muted">{item.category}</p></div><span className={`text-xs font-medium ${item.positive ? "text-success" : "text-content-strong"}`}>{item.value}</span></div>)}
      </> : <>
        <div className="mb-5 flex items-center gap-3"><span className="rounded-xl bg-warning-soft p-3 text-orange"><Target className="size-5" /></span><div><p className="text-[10px] text-content">Um passo de cada vez</p><p className="mt-1 text-xl font-semibold">Mais perto de realizar.</p></div></div>
        {[{ name: "Reserva de emergência", value: "R$ 8.000", target: "R$ 10.000", progress: "80%", color: "bg-brand" }, { name: "Próxima viagem", value: "R$ 3.000", target: "R$ 6.000", progress: "50%", color: "bg-orange" }].map(item => <div key={item.name} className="mt-4 rounded-xl border border-border p-3.5"><div className="flex justify-between text-xs font-medium"><span>{item.name}</span><span className="text-content">{item.progress}</span></div><div className="my-3 h-1.5 overflow-hidden rounded-full bg-surface-elevated"><div className={`h-full rounded-full ${item.color}`} style={{ width: item.progress }} /></div><p className="text-[10px] text-content"><strong className="font-medium text-content-strong">{item.value}</strong> de {item.target}</p></div>)}
        <p className="mt-4 flex items-center gap-2 text-[10px] text-success"><Check className="size-3" />Cada aporte conta para o seu futuro.</p>
      </>}
      <p className="mt-4 text-[9px] tracking-wide text-content-muted">PRÉVIA ILUSTRATIVA · DADOS FICTÍCIOS</p>
    </div>
  );
}
