import type {
ContributionDialogState,
ContributionFormState
} from "@/components/finance/goals/goals-types";

export interface GoalsViewOpenContributionDialogContext {
  setContributionForm: import("react").Dispatch<import("react").SetStateAction<ContributionFormState>>;
  dashboard: { investmentProjection: { currentBalanceCents: number; asOfDate: string; estimatedInterestCents: number; contributionCents: number; withdrawalCents: number; netMovementCents: number; projection: { [k: string]: number; }; plannedMovements: import("@/lib/investment-projection").InvestmentMovement[]; nextContributionDate: string | undefined; id: string; createdAt: Date & string; updatedAt: Date & string; checkpointBalanceCents: number; expectedMonthlyRateBps: number; checkpointDate: string; } | null; summary: { investmentBalanceCents: number; totalAllocatedCents: number; freeReserveCents: number; remainingToGoalsCents: number; monthlyRequiredCents: number; monthlyPlannedContributionCents: number; goalCount: number; archivedGoalCount: number; }; goals: { targetDate: string | null; allocatedCents: number; remainingCents: number; overfundedCents: number; progressPercentage: number; monthlyRequiredCents: number; notes: string | null; id: string; name: string; createdAt: Date & string; updatedAt: Date & string; status: "active" | "paused" | "completed" | "archived"; category: "other" | "housing" | "vehicle" | "electronics" | "travel" | "education" | "emergency"; targetAmountCents: number; plannedMonthlyContributionCents: number; priority: number; color: string; }[]; archivedGoals: { targetDate: string | null; allocatedCents: number; remainingCents: number; overfundedCents: number; progressPercentage: number; monthlyRequiredCents: number; notes: string | null; id: string; name: string; createdAt: Date & string; updatedAt: Date & string; status: "active" | "paused" | "completed" | "archived"; category: "other" | "housing" | "vehicle" | "electronics" | "travel" | "education" | "emergency"; targetAmountCents: number; plannedMonthlyContributionCents: number; priority: number; color: string; }[]; charts: { allocationBreakdown: { id: string; name: string; amountCents: number; color: string; }[]; monthlyEvolution: { cumulativeAllocatedCents: number; monthlyAllocatedCents: number; monthlyContributionCents: number; monthlyReleasedCents: number; netMovementCents: number; month: string; }[]; }; recentAllocations: { goalName: string; goalColor: string; notes: string | null; occurredOn: string; id: string; type: "contribution" | "initial_allocation" | "manual_allocation" | "manual_release" | "correction"; createdAt: Date & string; updatedAt: Date & string; amountCents: number; transactionId: string | null; goalId: string; }[]; options: { sourceAccounts: { id: string; name: string; }[]; investmentCategories: { id: string; name: string; }[]; goalCategories: ("other" | "housing" | "vehicle" | "electronics" | "travel" | "education" | "emergency")[]; goalStatuses: ("active" | "paused" | "completed" | "archived")[]; allocationTypes: ("contribution" | "initial_allocation" | "manual_allocation" | "manual_release" | "correction")[]; }; };
  setContributionDialog: import("react").Dispatch<import("react").SetStateAction<ContributionDialogState>>;
}
